language: python
python:
    - "2.7"
    - "3.4"
cache: 
    - pip
before_install:
    - pip install pytest pytest-cov
# command to run tests
script: nosetests

notifications: # set notification options
  email:
    recipients:
      - roh919@mail.usask.ca
      - henry621603@gmail.com

    # change is when the repo status goes from pass to fail or vice versa
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always