language: python
python:
    - "2.7"
    - "3.4"
cache: 
    - pip
    
# Whitelisting example
branches:
  only:
    - master

# Adopt code from:  https://ryanvarley.uk/solutions/2014/05/14/how-to-solve-travis-ci-matplotlib-tclerror-no-display/    
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "rm -rf ~/.cache/matplotlib"
    
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -r requirements.txt --use-mirrors
  - pip install -r test_requirements.txt --use-mirrors

# Adopt code from:  https://github.com/rossant/ipycache/blob/master/.travis.yml
script: 
    - python ipynb_runner.py -v -s LearnPython.ipynb
    - nosetests learnMatplotlib.py
    #- nosetests tex_demo.py

# set notification options
notifications: 
  email:
    recipients:
      - roh919@mail.usask.ca
      - henry621603@gmail.com

    # change is when the repo status goes from pass to fail or vice versa
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always